import type { DataSourceCategory, DataSourceCoverageType, DataSourceStatus } from '../src/types/data-source';

export interface SourceCatalogEntry {
  source_key: string;
  display_name: string;
  description: string;
  country: string;
  regulator_url: string;
  data_url: string;
  update_frequency: string;
  status: DataSourceStatus;
  notes: string | null;
  category: DataSourceCategory;
  coverage_type: DataSourceCoverageType;
}

export const SOURCE_CATEGORY_LABELS: Record<DataSourceCategory, string> = {
  institution_registry: 'Institution Registry',
  financial_filings: 'Financial Filings',
  holding_company: 'Holding Company',
  community_reinvestment: 'Community Reinvestment',
  payments_infrastructure: 'Payments Infrastructure',
  market_data: 'Market Data',
  complaint_data: 'Complaint Data',
  corporate_filings: 'Corporate Filings',
  licensing_registry: 'Licensing Registry',
};

export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  {
    source_key: 'fdic',
    display_name: 'FDIC BankFind Suite',
    description: 'FDIC-insured U.S. commercial banks and savings institutions with quarterly condition and branch data.',
    country: 'US',
    regulator_url: 'https://banks.data.fdic.gov',
    data_url: 'https://banks.data.fdic.gov/api/institutions',
    update_frequency: 'quarterly',
    status: 'active',
    notes: 'Primary bank core for U.S. depository institutions.',
    category: 'institution_registry',
    coverage_type: 'institutions',
  },
  {
    source_key: 'fdic_history',
    display_name: 'FDIC History API',
    description: 'Official FDIC institution history records for charter openings, mergers, failures, closures, and conversions.',
    country: 'US',
    regulator_url: 'https://api.fdic.gov/banks/history',
    data_url: 'https://api.fdic.gov/banks/history',
    update_frequency: 'daily',
    status: 'active',
    notes: 'Institution-level events only; branch rows are filtered out before writing charter_events.',
    category: 'institution_registry',
    coverage_type: 'records',
  },
  {
    source_key: 'ncua',
    display_name: 'NCUA Call Report Data',
    description: 'Federally insured U.S. credit union filings and quarterly financial condition data.',
    country: 'US',
    regulator_url: 'https://www.ncua.gov',
    data_url: 'https://www.ncua.gov/analysis/credit-union-corporate-call-report-data',
    update_frequency: 'quarterly',
    status: 'active',
    notes: 'Quarterly 5300-style credit union coverage.',
    category: 'financial_filings',
    coverage_type: 'institutions',
  },
  {
    source_key: 'osfi',
    display_name: 'OSFI Who We Regulate',
    description: 'Federally regulated Canadian financial institutions supervised by OSFI.',
    country: 'CA',
    regulator_url: 'https://www.osfi-bsif.gc.ca',
    data_url: 'https://www.osfi-bsif.gc.ca/en/supervision/who-we-regulate',
    update_frequency: 'daily',
    status: 'active',
    notes: 'Canadian regulated bank and insurer authority list.',
    category: 'institution_registry',
    coverage_type: 'institutions',
  },
  {
    source_key: 'rpaa',
    display_name: 'Bank of Canada RPAA Registry',
    description: 'Registered payment service providers under the Retail Payment Activities Act.',
    country: 'CA',
    regulator_url: 'https://www.bankofcanada.ca',
    data_url: 'https://www.bankofcanada.ca/core-functions/funds-management/retail-payments-supervision/',
    update_frequency: 'realtime',
    status: 'active',
    notes: 'Registry-backed PSP coverage for Canada.',
    category: 'licensing_registry',
    coverage_type: 'entities',
  },
  {
    source_key: 'ciro',
    display_name: 'CIRO Member Registry',
    description: 'Canadian Investment Regulatory Organization member firms and dealer lookup data.',
    country: 'CA',
    regulator_url: 'https://www.ciro.ca',
    data_url: 'https://www.ciro.ca/investors/check-your-advisor-dealer',
    update_frequency: 'monthly',
    status: 'active',
    notes: 'Dealer registry for securities and mutual fund participants.',
    category: 'licensing_registry',
    coverage_type: 'entities',
  },
  {
    source_key: 'fintrac',
    display_name: 'FINTRAC MSB Registry',
    description: 'Canadian money services businesses and foreign MSBs registered with FINTRAC.',
    country: 'CA',
    regulator_url: 'https://fintrac-canafe.canada.ca',
    data_url: 'https://www10.fintrac-canafe.gc.ca/msb-esm/public/msb-list/',
    update_frequency: 'realtime',
    status: 'active',
    notes: 'Includes Canadian MSBs and crypto-adjacent entities.',
    category: 'licensing_registry',
    coverage_type: 'entities',
  },
  {
    source_key: 'fincen',
    display_name: 'FinCEN MSB Registry',
    description: 'U.S. money services businesses and related MSB registry records.',
    country: 'US',
    regulator_url: 'https://www.fincen.gov',
    data_url: 'https://www.fincen.gov/msb-registrant-search',
    update_frequency: 'realtime',
    status: 'active',
    notes: 'Current repo has a starter loaded subset.',
    category: 'licensing_registry',
    coverage_type: 'entities',
  },
  {
    source_key: 'ffiec_cdr',
    display_name: 'FFIEC CDR Public Web Services',
    description: 'Public call report and UBPR access for banks and savings institutions via the Central Data Repository.',
    country: 'US',
    regulator_url: 'https://cdr.ffiec.gov/public/PWS/PWSPage.aspx',
    data_url: 'https://cdr.ffiec.gov/public/PWS/PWSPage.aspx',
    update_frequency: 'quarterly',
    status: 'pending',
    notes: 'Starter loader supports Panel of Reporters enrichment through the official PWS account flow; deeper facsimile ingestion remains a later warehouse phase.',
    category: 'financial_filings',
    coverage_type: 'institutions',
  },
  {
    source_key: 'ffiec_nic',
    display_name: 'FFIEC National Information Center',
    description: 'Holding company, affiliate, and structure data for U.S. banking organizations.',
    country: 'US',
    regulator_url: 'https://www.ffiec.gov/npw/',
    data_url: 'https://www.ffiec.gov/npw/FinancialReport/FinancialDataDownload',
    update_frequency: 'quarterly',
    status: 'pending',
    notes: 'Starter loader supports official NIC bulk files; manual local download is required because the public site is CAPTCHA-protected from plain scripted fetches.',
    category: 'holding_company',
    coverage_type: 'entities',
  },
  {
    source_key: 'ffiec_hmda',
    display_name: 'FFIEC HMDA',
    description: 'Mortgage disclosure and origination data published through FFIEC HMDA resources.',
    country: 'US',
    regulator_url: 'https://www.ffiec.gov/hmda',
    data_url: 'https://www.ffiec.gov/hmda',
    update_frequency: 'annual',
    status: 'pending',
    notes: 'Planned mortgage-market and fair-lending context.',
    category: 'market_data',
    coverage_type: 'records',
  },
  {
    source_key: 'ffiec_census',
    display_name: 'FFIEC Census and Geomap',
    description: 'Census tract and geomap context used for CRA and HMDA geographic analysis.',
    country: 'US',
    regulator_url: 'https://www.ffiec.gov',
    data_url: 'https://www.ffiec.gov/census',
    update_frequency: 'annual',
    status: 'pending',
    notes: 'Planned geographic benchmarking and tract overlays.',
    category: 'market_data',
    coverage_type: 'records',
  },
  {
    source_key: 'ffiec_cra',
    display_name: 'FFIEC CRA Ratings',
    description: 'Community Reinvestment Act public ratings and related disclosure context.',
    country: 'US',
    regulator_url: 'https://www.ffiec.gov',
    data_url: 'https://www.ffiec.gov/craratings/',
    update_frequency: 'quarterly',
    status: 'pending',
    notes: 'Current app uses some live enrichment but does not persist the source yet.',
    category: 'community_reinvestment',
    coverage_type: 'records',
  },
  {
    source_key: 'occ',
    display_name: 'OCC Financial Institution Lists',
    description: 'Official OCC institution lists, trust bank lists, and charter reference materials.',
    country: 'US',
    regulator_url: 'https://www.occ.treas.gov',
    data_url: 'https://www.occ.treas.gov/topics/charters-and-licensing/financial-institution-lists/index-financial-institution-lists.html',
    update_frequency: 'monthly',
    status: 'pending',
    notes: 'Planned charter-family and trust-bank expansion source.',
    category: 'institution_registry',
    coverage_type: 'institutions',
  },
  {
    source_key: 'frb_routing',
    display_name: 'FRB Routing Number Directory',
    description: 'Federal Reserve routing transit directory and payment rail participation context.',
    country: 'US',
    regulator_url: 'https://www.frbservices.org',
    data_url: 'https://www.frbservices.org/resources/routing-number-directory/',
    update_frequency: 'daily',
    status: 'pending',
    notes: 'Planned payments-infrastructure context for rails and routing status.',
    category: 'payments_infrastructure',
    coverage_type: 'records',
  },
  {
    source_key: 'sec_edgar',
    display_name: 'SEC EDGAR APIs',
    description: 'Public company filings and structured SEC company data for listed banks and fintechs.',
    country: 'US',
    regulator_url: 'https://www.sec.gov',
    data_url: 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',
    update_frequency: 'daily',
    status: 'pending',
    notes: 'Planned public-company parent, issuer, and fintech filing context.',
    category: 'corporate_filings',
    coverage_type: 'filings',
  },
  {
    source_key: 'cfpb_complaints',
    display_name: 'CFPB Consumer Complaint Database',
    description: 'Public complaint data covering consumer financial products and institutions.',
    country: 'US',
    regulator_url: 'https://www.consumerfinance.gov',
    data_url: 'https://www.consumerfinance.gov/data-research/consumer-complaints/',
    update_frequency: 'daily',
    status: 'active',
    notes: 'Complaint-signal layer using company suggestions and official CFPB trend aggregates.',
    category: 'complaint_data',
    coverage_type: 'complaints',
  },
  {
    source_key: 'nmls',
    display_name: 'NMLS Consumer Access',
    description: 'State-licensed nonbank and mortgage licensing lookup through NMLS Consumer Access.',
    country: 'US',
    regulator_url: 'https://www.csbs.org/nonbank-licensing-and-examination',
    data_url: 'https://www.nmlsconsumeraccess.org/',
    update_frequency: 'daily',
    status: 'pending',
    notes: 'Planned state-licensed nonbank expansion.',
    category: 'licensing_registry',
    coverage_type: 'entities',
  },
  {
    source_key: 'cmhc',
    display_name: 'CMHC Housing Data',
    description: 'Canadian housing and mortgage market data from Canada Mortgage and Housing Corporation.',
    country: 'CA',
    regulator_url: 'https://www.cmhc-schl.gc.ca',
    data_url: 'https://www.cmhc-schl.gc.ca/en/data-and-research',
    update_frequency: 'monthly',
    status: 'active',
    notes: 'Aggregate Canadian housing and mortgage context.',
    category: 'market_data',
    coverage_type: 'series',
  },
  {
    source_key: 'boc',
    display_name: 'Bank of Canada Valet API',
    description: 'Bank of Canada policy rates, market series, and macro reference data.',
    country: 'CA',
    regulator_url: 'https://www.bankofcanada.ca',
    data_url: 'https://www.bankofcanada.ca/valet/docs',
    update_frequency: 'realtime',
    status: 'active',
    notes: 'Aggregate market and policy series only.',
    category: 'market_data',
    coverage_type: 'series',
  },
];
